name: Linting

on: [push]

jobs:
  linting:
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: ["ubuntu", "macos"]
    continue-on-error: false

    steps:

    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        environment-file: environment.yml
        activate-environment: helx
        auto-activate-base: false

    - name: Check code quality
      id: linting
      run: |
        pip install pylint
        MESSAGE=$(pylint -ry $(git ls-files '*.py') ||:)
        echo "$MESSAGE"

    - name: Check for reproducibility
      run: |
        conda info --envs
        conda env list
        conda list
        pip install -e .
        python -c "import helx"

    - name: Run examples
      run: |
        conda info --envs
        conda env list
        conda list
        pip install -e .
        python download_extras.py
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.mujoco/mujoco210/bin:/usr/lib/nvidia
        export CPATH=$CONDA_PREFIX/include
        wandb login ${{ secrets.WANDB_API_KEY }}
        for f in examples/*.py; do python "$f"; done
